CREATE TABLE machine(
`NO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`MachineNO` VARCHAR(20) NOT NULL,
`MachineName` VARCHAR(20) NOT NULL,
PRIMARY KEY(`NO`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;