CREATE TABLE device_info_machine(
`NO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`DeviceNO` VARCHAR(20) NOT NULL,
`MachineNO` VARCHAR(20) NOT NULL,
`LocationX` VARCHAR(20) NOT NULL,
`LocationY` VARCHAR(20) NOT NULL,
PRIMARY KEY(`NO`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;