/*
 Navicat Premium Data Transfer

 Source Server         : learning
 Source Server Type    : MySQL
 Source Server Version : 50726
 Source Host           : localhost:3306
 Source Schema         : cloud_manage

 Target Server Type    : MySQL
 Target Server Version : 50726
 File Encoding         : 65001

 Date: 07/12/2021 09:49:47
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for device
-- ----------------------------
DROP TABLE IF EXISTS `device`;
CREATE TABLE `device`  (
  `NO` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeviceNO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DeviceName` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `MachineNO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `LocationX` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `LocationY` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ValidParaCount` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para1Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para1NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para1SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para1MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para1MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para2Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para2NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para2SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para2MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para2MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para3Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para3NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para3SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para3MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para3MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para4Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para4NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para4SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para4MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para4MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para5Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para5NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para5SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para5MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para5MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para6Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para6NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para6SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para6MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para6MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para7Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para7NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para7SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para7MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para7MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para8Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para8NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para8SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para8MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para8MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para9Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para9NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para9SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para9MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para9MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para10Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para10NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para10SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para10MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para10MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para11Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para11NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para11SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para11MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para11MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para12Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para12NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para12SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para12MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para12MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para13Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para13NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para13SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para13MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para13MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para14Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para14NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para14SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para14MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para14MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para15Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para15NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para15SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para15MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para15MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para16Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para16Name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para16Suffix` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para16Min` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para16Max` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para17Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para17NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para17SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para17MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para17MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para18Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para18NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para18SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para18MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para18MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para19Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para19NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para19SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para19MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para19MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para20Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para20NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para20SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para20MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para20MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para21Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para21NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para21SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para21MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para21MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para22Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para22NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para22SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para22MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para22MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para23Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para23NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para23SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para23MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para23MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para24Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para24NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para24SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para24MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para24MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para25Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para25NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para25SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para25MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para25MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para26Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para26NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para26SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para26MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para26MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para27Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para27NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para27SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para27MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para27MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para28Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para28NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para28SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para28MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para28MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para29Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para29NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para29SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para29MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para29MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para30Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para30NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para30SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para30MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para30MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para31Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para31NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para31SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para31MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para31MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para32Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para32NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para32SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para32MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para32MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para33Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para33NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para33SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para33MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para33MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para34Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para34NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para34SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para34MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para34MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para35Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para35NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para35SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para35MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para35MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para36Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para36NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para36SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para36MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para36MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para37Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para37NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para37SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para37MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para37MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para38Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para38NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para38SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para38MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para38MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para39Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para39NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para39SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para39MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para39MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para40Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para40NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para40SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para40MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para40MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para41Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para41NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para41SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para41MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para41MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para42Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para42NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para42SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para42MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para42MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para43Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para43NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para43SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para43MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para43MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para44Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para44NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para44SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para44MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para44MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para45Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para45NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para45SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para45MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para45MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para46Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para46NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para46SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para46MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para46MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47Name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47Suffix` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47Min` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47Max` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para47MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para48Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para48NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para48SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para48MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para48MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para49Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para49NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para49SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para49MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para49MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para50Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para50NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para50SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para50MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para50MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para51Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para51NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para51SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para51MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para51MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para52Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para52NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para52SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para52MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para52MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para53Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para53NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para53SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para53MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para53MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para54Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para54NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para54SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para54MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para54MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para55Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para55NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para55SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para55MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para55MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para56Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para56NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para56SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para56MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para56MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para57Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para57NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para57SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para57MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para57MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para58Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para58NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para58SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para58MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para58MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para59Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para59NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para59SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para59MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para59MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para60Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para60NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para60SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para60MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para60MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para61Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para61NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para61SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para61MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para61MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para62Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para62NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para62SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para62MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para62MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para63Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para63NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para63SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para63MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para63MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para64Default` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para64NameDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para64SuffixDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para64MinDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Para64MaxDefault` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`NO`) USING BTREE,
  UNIQUE INDEX `NO`(`NO`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 19 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of device
-- ----------------------------
INSERT INTO `device` VALUES (1, '001', '烟库乱烟检测', '001', '550', '554', '5', '100', '检测数量', '件', '0', '100', '23', '缺陷数量', '件', '0', '10', '60', 'CPU温度', '℃', '0', '60', '50', 'CPU利用率', '%', '0', '90', '30', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (2, '002', '烟支空头检测', '002', '550', '770', '5', '100', '检测数量', '件', '0', '100', '42', '缺陷数量', '件', '0', '10', '70', 'CPU温度', '℃', '0', '60', '60', 'CPU利用率', '%', '0', '90', '40', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (3, '003', '模盒缺支检测', '003', '1198', '554', '5', '100', '检测数量', '件', '0', '100', '22', '缺陷数量', '件', '0', '10', '65', 'CPU温度', '℃', '0', '60', '66', 'CPU利用率', '%', '0', '90', '50', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (4, '004', '一号轮缺支检测', '004', '550', '554', '5', '100', '检测数量', '件', '0', '100', '11', '缺陷数量', '件', '0', '10', '75', 'CPU温度', '℃', '0', '60', '55', 'CPU利用率', '%', '0', '90', '60', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (5, '005', '三号轮铝箔纸检测', '005', '550', '770', '5', '100', '检测数量', '件', '0', '100', '6', '缺陷数量', '件', '0', '10', '80', 'CPU温度', '℃', '0', '60', '40', 'CPU利用率', '%', '0', '90', '70', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (6, '006', '四号轮铝箔纸检测', '006', '1198', '554', '5', '100', '检测数量', '件', '0', '100', '23', '缺陷数量', '件', '0', '10', '60', 'CPU温度', '℃', '0', '60', '50', 'CPU利用率', '%', '0', '90', '30', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (7, '007', '五号轮内框纸检测', '101', '550', '554', '5', '100', '检测数量', '件', '0', '100', '42', '缺陷数量', '件', '0', '10', '70', 'CPU温度', '℃', '0', '60', '60', 'CPU利用率', '%', '0', '90', '40', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (8, '008', '小包外观检测', '102', '550', '770', '5', '100', '检测数量', '件', '0', '100', '22', '缺陷数量', '件', '0', '10', '65', 'CPU温度', '℃', '0', '60', '66', 'CPU利用率', '%', '0', '90', '50', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (9, '009', '烟包外观复检', '103', '1198', '554', '5', '100', '检测数量', '件', '0', '100', '11', '缺陷数量', '件', '0', '10', '75', 'CPU温度', '℃', '0', '60', '55', 'CPU利用率', '%', '0', '90', '60', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (10, '010', '小包拉线检测', '104', '550', '554', '5', '100', '检测数量', '件', '0', '100', '6', '缺陷数量', '件', '0', '10', '80', 'CPU温度', '℃', '0', '60', '40', 'CPU利用率', '%', '0', '90', '70', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (11, '011', '散包视觉检测', '105', '550', '770', '5', '100', '检测数量', '件', '0', '100', '23', '缺陷数量', '件', '0', '10', '60', 'CPU温度', '℃', '0', '60', '50', 'CPU利用率', '%', '0', '90', '30', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (12, '012', '散包光电检测', '106', '1198', '554', '5', '100', '检测数量', '件', '0', '100', '42', '缺陷数量', '件', '0', '10', '70', 'CPU温度', '℃', '0', '60', '60', 'CPU利用率', '%', '0', '90', '40', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (13, '013', '条盒拉线检测', '107', '550', '554', '5', '100', '检测数量', '件', '0', '100', '22', '缺陷数量', '件', '0', '10', '65', 'CPU温度', '℃', '0', '60', '66', 'CPU利用率', '%', '0', '90', '50', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (14, '101', '_烟库乱烟检测', '108', '550', '770', '5', '100', '检测数量', '件', '0', '100', '22', '缺陷数量', '件', '0', '10', '65', 'CPU温度', '℃', '0', '60', '66', 'CPU利用率', '%', '0', '90', '50', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (15, '102', '_烟支空头检测', '109', '1198', '554', '5', '100', '检测数量', '件', '0', '100', '22', '缺陷数量', '件', '0', '10', '65', 'CPU温度', '℃', '0', '60', '66', 'CPU利用率', '%', '0', '90', '50', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (16, '103', '_模盒缺支检测', '001', '550', '554', '5', '100', '检测数量', '件', '0', '100', '11', '缺陷数量', '件', '0', '10', '75', 'CPU温度', '℃', '0', '60', '55', 'CPU利用率', '%', '0', '90', '60', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (17, '104', '_一号轮缺支检测', '002', '550', '770', '5', '100', '检测数量', '件', '0', '100', '6', '缺陷数量', '件', '0', '10', '80', 'CPU温度', '℃', '0', '60', '40', 'CPU利用率', '%', '0', '90', '70', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');
INSERT INTO `device` VALUES (18, '105', '_三号轮铝箔纸检测', '003', '1198', '554', '5', '100', '检测数量', '件', '0', '100', '23', '缺陷数量', '件', '0', '10', '60', 'CPU温度', '℃', '0', '60', '50', 'CPU利用率', '%', '0', '90', '30', '内存利用率', '%', '0', '90', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '', '', '', '', '', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\');

SET FOREIGN_KEY_CHECKS = 1;
