CREATE TABLE productionLine(
`NO` INT UNSIGNED AUTO_INCREMENT UNIQUE,
`LineNO` VARCHAR(255) NOT NULL,
`LineName` VARCHAR(255) NOT NULL,
PRIMARY KEY(`NO`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;