CREATE TABLE faults_config(
`NO` INT UNSIGNED AUTO_INCREMENT,
`LineNO` VARCHAR(255) NOT NULL,
`DeviceNO` VARCHAR(255) NOT NULL,
`FaultNO` VARCHAR(255) NOT NULL,
`FaultEnable` VARCHAR(255) NOT NULL,
PRIMARY KEY(`NO`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;