CREATE TABLE device(
`NO` INT UNSIGNED AUTO_INCREMENT UNIQUE,
`DeviceNO` VARCHAR(255) NOT NULL,
`DeviceName`	VARCHAR(255) NOT NULL,
PRIMARY KEY(`NO`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;