CREATE TABLE faults(
`NO` INT UNSIGNED AUTO_INCREMENT,
`DeviceNO` VARCHAR(255) NOT NULL,
`FaultNO`	VARCHAR(255) NOT NULL,
`FaultName`	VARCHAR(255) NOT NULL,
`FaultEnable`	VARCHAR(255) NOT NULL,
PRIMARY KEY(`NO`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;